"""add unique

Revision ID: 0b87c1eaa6a8
Revises: de4e1913f970
Create Date: 2025-08-21 14:01:51.324248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b87c1eaa6a8'
down_revision: Union[str, Sequence[str], None] = 'de4e1913f970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_role_code'), table_name='t_role')
    op.create_index(op.f('ix_t_role_code'), 't_role', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_role_code'), table_name='t_role')
    op.create_index(op.f('ix_t_role_code'), 't_role', ['code'], unique=False)
    # ### end Alembic commands ###
