"""add checklist store

Revision ID: 212c959546c3
Revises: b28104285122
Create Date: 2025-08-21 21:05:17.734514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212c959546c3'
down_revision: Union[str, Sequence[str], None] = 'b28104285122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_store_checklist',
    sa.Column('id_store_checklist', sa.Integer(), nullable=False),
    sa.Column('id_checklist', sa.Integer(), nullable=True),
    sa.Column('id_store', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_store_checklist')
    )
    op.create_index(op.f('ix_t_store_checklist_id_checklist'), 't_store_checklist', ['id_checklist'], unique=False)
    op.create_index(op.f('ix_t_store_checklist_id_store'), 't_store_checklist', ['id_store'], unique=False)
    op.create_index(op.f('ix_t_store_checklist_id_store_checklist'), 't_store_checklist', ['id_store_checklist'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_store_checklist_id_store_checklist'), table_name='t_store_checklist')
    op.drop_index(op.f('ix_t_store_checklist_id_store'), table_name='t_store_checklist')
    op.drop_index(op.f('ix_t_store_checklist_id_checklist'), table_name='t_store_checklist')
    op.drop_table('t_store_checklist')
    # ### end Alembic commands ###
