"""role checklist and commentary field

Revision ID: 25d8f7a59a0b
Revises: 73a8c9c59959
Create Date: 2025-08-27 15:35:48.086593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d8f7a59a0b'
down_revision: Union[str, Sequence[str], None] = '73a8c9c59959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_role_checklist',
    sa.Column('id_role_checklist', sa.Integer(), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.Column('id_checklist', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_role_checklist', name=op.f('pk_t_role_checklist'))
    )
    op.create_index(op.f('ix_t_role_checklist_id_checklist'), 't_role_checklist', ['id_checklist'], unique=False)
    op.create_index(op.f('ix_t_role_checklist_id_role'), 't_role_checklist', ['id_role'], unique=False)
    op.create_index(op.f('ix_t_role_checklist_id_role_checklist'), 't_role_checklist', ['id_role_checklist'], unique=False)
    op.add_column('t_checklist_user_report', sa.Column('commentary', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_checklist_user_report', 'commentary')
    op.drop_index(op.f('ix_t_role_checklist_id_role_checklist'), table_name='t_role_checklist')
    op.drop_index(op.f('ix_t_role_checklist_id_role'), table_name='t_role_checklist')
    op.drop_index(op.f('ix_t_role_checklist_id_checklist'), table_name='t_role_checklist')
    op.drop_table('t_role_checklist')
    # ### end Alembic commands ###
