"""init migration

Revision ID: 27d537de5d6a
Revises: 
Create Date: 2025-08-04 00:48:38.029371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d537de5d6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_checklist',
    sa.Column('id_checklist', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_checklist')
    )
    op.create_index(op.f('ix_t_checklist_id_checklist'), 't_checklist', ['id_checklist'], unique=False)
    op.create_index(op.f('ix_t_checklist_title'), 't_checklist', ['title'], unique=False)
    op.create_table('t_role',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_role')
    )
    op.create_index(op.f('ix_t_role_code'), 't_role', ['code'], unique=False)
    op.create_index(op.f('ix_t_role_id_role'), 't_role', ['id_role'], unique=False)
    op.create_index(op.f('ix_t_role_name'), 't_role', ['name'], unique=False)
    op.create_table('t_user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('surname', sa.String(length=50), nullable=True),
    sa.Column('patronymic', sa.String(length=50), nullable=True),
    sa.Column('mail', sa.String(length=150), nullable=True),
    sa.Column('login', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('mail')
    )
    op.create_index(op.f('ix_t_user_id_user'), 't_user', ['id_user'], unique=False)
    op.create_table('t_user_checklist',
    sa.Column('id_user_checklist', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_checklist', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_checklist'], ['t_user.id_user'], ),
    sa.ForeignKeyConstraint(['id_user'], ['t_checklist.id_checklist'], ),
    sa.PrimaryKeyConstraint('id_user_checklist')
    )
    op.create_index(op.f('ix_t_user_checklist_id_user_checklist'), 't_user_checklist', ['id_user_checklist'], unique=False)
    op.create_table('t_user_role',
    sa.Column('id_user_role', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_role'], ['t_role.id_role'], ),
    sa.ForeignKeyConstraint(['id_user'], ['t_user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user_role')
    )
    op.create_index(op.f('ix_t_user_role_id_user_role'), 't_user_role', ['id_user_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_user_role_id_user_role'), table_name='t_user_role')
    op.drop_table('t_user_role')
    op.drop_index(op.f('ix_t_user_checklist_id_user_checklist'), table_name='t_user_checklist')
    op.drop_table('t_user_checklist')
    op.drop_index(op.f('ix_t_user_id_user'), table_name='t_user')
    op.drop_table('t_user')
    op.drop_index(op.f('ix_t_role_name'), table_name='t_role')
    op.drop_index(op.f('ix_t_role_id_role'), table_name='t_role')
    op.drop_index(op.f('ix_t_role_code'), table_name='t_role')
    op.drop_table('t_role')
    op.drop_index(op.f('ix_t_checklist_title'), table_name='t_checklist')
    op.drop_index(op.f('ix_t_checklist_id_checklist'), table_name='t_checklist')
    op.drop_table('t_checklist')
    # ### end Alembic commands ###
