"""role parent

Revision ID: 2ee0fe0899df
Revises: 212c959546c3
Create Date: 2025-08-24 09:01:08.663892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee0fe0899df'
down_revision: Union[str, Sequence[str], None] = '212c959546c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_role', sa.Column('id_parent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_role', 'id_parent')
    # ### end Alembic commands ###
