"""roles script

Revision ID: 4e0ae656fd1f
Revises: 5e9763b87d21
Create Date: 2025-08-18 15:35:26.631310

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e0ae656fd1f"
down_revision: Union[str, Sequence[str], None] = "5e9763b87d21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        insert into checklist.t_role(name, code)
        values('Администратор', 'admin'),
        ('Смертный', 'report_user')
        """
    )
    op.execute(
        """
        insert into checklist.t_user_role(id_user, id_role)
        values(1, 1)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("delete from checklist.t_role where code in ('admin', 'report_user')")
    # ### end Alembic commands ###
