"""add_report

Revision ID: 5e9763b87d21
Revises: bedeb89db668
Create Date: 2025-08-16 11:50:38.724270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e9763b87d21'
down_revision: Union[str, Sequence[str], None] = 'bedeb89db668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_checklist_user_report',
    sa.Column('id_checklist_user_report', sa.Integer(), nullable=False),
    sa.Column('id_checklist', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_checklist_user_report')
    )
    op.create_index(op.f('ix_t_checklist_user_report_id_checklist_user_report'), 't_checklist_user_report', ['id_checklist_user_report'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_checklist_user_report_id_checklist_user_report'), table_name='t_checklist_user_report')
    op.drop_table('t_checklist_user_report')
    # ### end Alembic commands ###
