"""naming convention

Revision ID: 73a8c9c59959
Revises: fdd980a40bae
Create Date: 2025-08-26 15:26:55.937294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a8c9c59959'
down_revision: Union[str, Sequence[str], None] = 'fdd980a40bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('t_user_login_key'), 't_user', type_='unique')
    op.create_unique_constraint(op.f('uq_t_user_login'), 't_user', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_t_user_login'), 't_user', type_='unique')
    op.create_unique_constraint(op.f('t_user_login_key'), 't_user', ['login'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
