"""remove uniq

Revision ID: b28104285122
Revises: 0b87c1eaa6a8
Create Date: 2025-08-21 14:49:00.624634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b28104285122'
down_revision: Union[str, Sequence[str], None] = '0b87c1eaa6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('t_employee_mail_key'), 't_employee', type_='unique')
    # op.drop_constraint(op.f('t_user_mail_key'), 't_user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(op.f('t_user_mail_key'), 't_user', ['mail'], postgresql_nulls_not_distinct=False)
    # op.create_unique_constraint(op.f('t_employee_mail_key'), 't_employee', ['mail'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
