"""roles_stores_employees

Revision ID: de4e1913f970
Revises: 4e0ae656fd1f
Create Date: 2025-08-21 10:38:22.159562

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de4e1913f970"
down_revision: Union[str, Sequence[str], None] = "4e0ae656fd1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "t_employee",
        sa.Column("id_employee", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("surname", sa.String(length=50), nullable=True),
        sa.Column("patronymic", sa.String(length=50), nullable=True),
        sa.Column("mail", sa.String(length=150), nullable=True),
        sa.PrimaryKeyConstraint("id_employee"),
        sa.UniqueConstraint("mail"),
    )
    op.create_index(
        op.f("ix_t_employee_id_employee"), "t_employee", ["id_employee"], unique=False
    )
    op.create_table(
        "t_store",
        sa.Column("id_store", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("code", sa.String(length=255), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id_store"),
    )
    op.create_index(op.f("ix_t_store_code"), "t_store", ["code"], unique=False)
    op.create_index(op.f("ix_t_store_id_store"), "t_store", ["id_store"], unique=False)
    op.create_index(op.f("ix_t_store_name"), "t_store", ["name"], unique=False)
    op.create_table(
        "t_store_employee",
        sa.Column("id_store_employee", sa.Integer(), nullable=False),
        sa.Column("id_employee", sa.Integer(), nullable=True),
        sa.Column("id_store", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id_store_employee"),
    )
    op.create_index(
        op.f("ix_t_store_employee_id_employee"),
        "t_store_employee",
        ["id_employee"],
        unique=False,
    )
    op.create_index(
        op.f("ix_t_store_employee_id_store"),
        "t_store_employee",
        ["id_store"],
        unique=False,
    )
    op.create_index(
        op.f("ix_t_store_employee_id_store_employee"),
        "t_store_employee",
        ["id_store_employee"],
        unique=False,
    )
    op.create_table(
        "t_store_user",
        sa.Column("id_store_user", sa.Integer(), nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=True),
        sa.Column("id_store", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id_store_user"),
    )
    op.create_index(
        op.f("ix_t_store_user_id_store"), "t_store_user", ["id_store"], unique=False
    )
    op.create_index(
        op.f("ix_t_store_user_id_store_user"),
        "t_store_user",
        ["id_store_user"],
        unique=False,
    )
    op.create_index(
        op.f("ix_t_store_user_id_user"), "t_store_user", ["id_user"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_t_store_user_id_user"), table_name="t_store_user")
    op.drop_index(op.f("ix_t_store_user_id_store_user"), table_name="t_store_user")
    op.drop_index(op.f("ix_t_store_user_id_store"), table_name="t_store_user")
    op.drop_table("t_store_user")
    op.drop_index(
        op.f("ix_t_store_employee_id_store_employee"), table_name="t_store_employee"
    )
    op.drop_index(op.f("ix_t_store_employee_id_store"), table_name="t_store_employee")
    op.drop_index(
        op.f("ix_t_store_employee_id_employee"), table_name="t_store_employee"
    )
    op.drop_table("t_store_employee")
    op.drop_index(op.f("ix_t_store_name"), table_name="t_store")
    op.drop_index(op.f("ix_t_store_id_store"), table_name="t_store")
    op.drop_index(op.f("ix_t_store_code"), table_name="t_store")
    op.drop_table("t_store")
    op.drop_index(op.f("ix_t_employee_id_employee"), table_name="t_employee")
    op.drop_table("t_employee")
    # ### end Alembic commands ###
