"""add component base role

Revision ID: fdd980a40bae
Revises: 2ee0fe0899df
Create Date: 2025-08-24 10:46:54.160349

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fdd980a40bae"
down_revision: Union[str, Sequence[str], None] = "2ee0fe0899df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "t_component",
        sa.Column("id_component", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("code", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id_component"),
    )
    op.create_index(op.f("ix_t_component_code"), "t_component", ["code"], unique=True)
    op.create_index(
        op.f("ix_t_component_id_component"),
        "t_component",
        ["id_component"],
        unique=False,
    )
    op.create_index(op.f("ix_t_component_name"), "t_component", ["name"], unique=False)
    op.create_table(
        "t_role_component",
        sa.Column("id_role_component", sa.Integer(), nullable=False),
        sa.Column("id_role", sa.Integer(), nullable=True),
        sa.Column("id_component", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id_role_component"),
    )
    op.create_index(
        op.f("ix_t_role_component_id_component"),
        "t_role_component",
        ["id_component"],
        unique=False,
    )
    op.create_index(
        op.f("ix_t_role_component_id_role"),
        "t_role_component",
        ["id_role"],
        unique=False,
    )
    op.create_index(
        op.f("ix_t_role_component_id_role_component"),
        "t_role_component",
        ["id_role_component"],
        unique=False,
    )
    op.add_column(
        "t_checklist_user_report", sa.Column("id_employee", sa.Integer(), nullable=True)
    )

    op.execute("""
        
        insert into checklist.t_component(name, code)
        values ('Доступ к конструктору', 'constructor'),
        ('Доступ к отчетам','report'),
        ('Доступ к заполнению чеклистов','checklist')
               
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("t_checklist_user_report", "id_employee")
    op.drop_index(
        op.f("ix_t_role_component_id_role_component"), table_name="t_role_component"
    )
    op.drop_index(op.f("ix_t_role_component_id_role"), table_name="t_role_component")
    op.drop_index(
        op.f("ix_t_role_component_id_component"), table_name="t_role_component"
    )
    op.drop_table("t_role_component")
    op.drop_index(op.f("ix_t_component_name"), table_name="t_component")
    op.drop_index(op.f("ix_t_component_id_component"), table_name="t_component")
    op.drop_index(op.f("ix_t_component_code"), table_name="t_component")
    op.drop_table("t_component")
    # ### end Alembic commands ###
